version: '3.8'
services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=funds
      - DB_USER=postgres
      - DB_PASSWORD=donip123

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: funds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: donip123
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  db-data:
