version: '3.8'
services:
  app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}

  # db:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   ports:
  #     - "5434:5432"

# volumes:
#   db-data:
